
server:
  port: 8007

management:
  health:
    defaults:
      enabled: false
  endpoint:
    shutdown:
      enabled: false
  security:
    enabled: false

logging:
  level:
    root: info
    com.blueskykong.tm.core: debug
  path: "./logs"

---
#spring:
#  cloud:
#    stream:
#      bindings:
#        test-input:
#          group: testGroup
#          content-type: application/x-java-object;type=com.blueskykong.springboot.rabbitmq.entity.TransactionMsg
#          destination: tx-test
#          binder: rabbit1
#      binders:
#        rabbit1:
#          type: rabbit
#          environment:
#            spring:
#              rabbitmq:
#                host: 120.55.43.136
#                port: 5672
#                username: guest
#                password: guest
#                virtual-host: /

---
tx:
  enabled: true
  core:
    compensation-cache-type: redis
    tx-redis-config:
      host-name: 192.168.1.200
      port: 6378
      password: Superid123
    serializer: kryo
    netty-serializer: kryo
    blocking-queue-type: Linked
    compensation: false
    tx-manager-id: lotor